"""T3: submission-side amendments from the venue research."""
from pathlib import Path

p = Path("paper/main.tex")
s = p.read_text(encoding="utf-8")
n = 0


def sub(old, new):
    global s, n
    assert old in s, "anchor missing:\n" + old[:140]
    s = s.replace(old, new, 1)
    n += 1


# --- T3.3: CCS concepts and keywords ---------------------------------------
sub("""\\ccsdesc[500]{Security and privacy~Intrusion detection systems}
\\ccsdesc[300]{Computing methodologies~Machine learning}

\\keywords{intrusion detection, streaming evaluation, benchmark construction,
experimental design, reproducibility, provenance}""",
    """\\ccsdesc[500]{Security and privacy~Intrusion detection systems}
\\ccsdesc[300]{Computing methodologies~Machine learning}
\\ccsdesc[300]{General and reference~Evaluation}

\\keywords{streaming network intrusion detection, benchmark stream
construction, evaluation methodology, experimental design, conformal risk
control, reproducibility, provenance}""")

# --- T3.2: cite and distinguish the 2026 concurrent work -------------------
sub("""\\textbf{Conformal and calibrated alerting.} Laxhammar and
Falkman~\\cite{laxhammar2014conformal} established conformal anomaly detection
for sequential data, with guarantees inherited from exchangeability
assumptions~\\cite{vovk2005alrw}; FADES~\\cite{barrett2026fades} applies
conformal signals to drift estimation for streaming IDS.""",
    """\\textbf{Conformal and calibrated alerting.} Laxhammar and
Falkman~\\cite{laxhammar2014conformal} established conformal anomaly detection
for sequential data, with guarantees inherited from exchangeability
assumptions~\\cite{vovk2005alrw}. Three 2026 lines are concurrent with this
work and distinct from it. FIRCE~\\cite{barrett2026firce} and its successor
FADES~\\cite{barrett2026fades} integrate conformal evaluation into streaming
IDS pipelines to drive drift detection and adaptive retraining; both propose
detection machinery and evaluate it, whereas this paper proposes no detector
and instead audits what an evaluation pipeline measures. Gurjar and
Camp~\\cite{gurjar2026tailrisk} forecast tail-risk escalation in enterprise
IDS alert streams using extreme-value methods on 251 million Suricata alerts;
that is a forecasting task on operational alert volume, not a benchmark
assembly question. None of the three examines how capture files are assembled
into an evaluation stream, which is the question here.""")

# --- T3.1: ACM-compliant GenAI statement, anonymity-preserving -------------
sub("""\\section*{Statement on Generative AI Usage}
Large language models were used, under continuous human direction, for
engineering assistance: writing and refactoring analysis scripts, drafting
prose subsequently verified against the archived measurements, and operating an
adversarial review harness that audited the authors' own claims. Every number
was produced by executed code with an archived manifest, not by a language
model; the claim ledger and provenance gate exist in part to make that boundary
auditable. The authors take full responsibility for all content.""",
    """\\section*{Acknowledgements: Generative AI Usage}
In accordance with the ACM Policy on Authorship, the authors disclose that
generative AI tools were used in the production of this work. Large language
models were used, under continuous human direction, to write and refactor
analysis scripts, to draft prose that was subsequently verified against the
archived measurements, and to operate an adversarial review harness that
audited the authors' own claims. No generative AI tool is an author of this
work, and none produced any reported number: every number was generated by
executed code that wrote an archived run manifest in the same execution, and
the provenance gate and claim ledger exist in part to make that boundary
externally auditable. The authors take full responsibility for the entire
content of this work, including any portion drafted with such assistance.""")

# --- T3.4: artifact availability, prominent and anonymized -----------------
sub("""\\section*{Data and Artifact Availability}""",
    """\\section*{Data and Artifact Availability}
\\label{sec:artifact}""")

p.write_text(s, encoding="utf-8")
print("applied %d T3 edits" % n)
